# Generated by Django 3.2.12 on 2022-05-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('posterurl', models.TextField()),
                ('tagline', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('vote_average', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genres')),
            ],
        ),
    ]
