# Generated by Django 3.2.12 on 2022-05-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_comments_reviews_userclickedmovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenreMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(max_length=10)),
                ('genre2', models.CharField(max_length=10)),
                ('genre3', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserClickedMovies',
        ),
    ]
